version: '3.8'

services:
  app:
    container_name: automacao-app
    build:
      context: .
    volumes:
      - ./:/app
    command: yarn start
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: